version: 2

jobs:
  test-frontend:
    docker:
      - image: circleci/node:6.11.4
    steps:
      - checkout
      - run:
          name: install yarn
          command: 'sudo npm install -g yarn --quiet'

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: yarn install
          command: 'yarn install --pure-lockfile --no-progress'

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: frontend tests
          command: './scripts/circle-test-frontend.sh'

  test-backend:
    docker:
      - image: circleci/golang:1.9.3
    working_directory: /go/src/github.com/grafana/grafana
    steps:
      - checkout
      - run:
          name: build backend and run go tests
          command: './scripts/circle-test-backend.sh'

  build:
    docker:
     - image: grafana/build-container:v0.1
    working_directory: /go/src/github.com/grafana/grafana
    steps:
      - checkout
      - run:
          name: build and package grafana
          command: './scripts/build/build.sh'
      - run:
          name: sign packages
          command: './scripts/build/sign_packages.sh'
      - run:
          name: sha-sum packages
          command: 'go run build.go sha-dist'
      - persist_to_workspace:
          root: dist
          paths:
            - grafana*

  deploy-master:
    docker:
      - image: circleci/python:2.7-stretch
    working_directory: /go/src/github.com/grafana/grafana
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: install awscli
          command: 'sudo pip install awscli'
      - run:
          name: fake deploy
          command: 'ls -ltr dist'
      - run:
          name: deploy to s3
          command: 'aws s3 sync --dryrun ./dist s3://$BUCKET_NAME/master'

  release:
    docker:
      - image: circleci/python:2.7-stretch
    working_directory: /go/src/github.com/grafana/grafana
    steps:
      - attach_workspace:
          at: dist
      - run:
          name: install awscli
          command: 'sudo pip install awscli'
      - run:
          name: fake deploy
          command: 'ls -ltr dist'
      - run:
          name: deploy to s3
          command: 'aws s3 sync --dryrun ./dist s3://$BUCKET_NAME/release'

# windows build trigger
# docker build trigger
#publish to grafanacom

workflows:
  version: 2
  test-and-build:
    jobs:
      - test-frontend:
          filters:
            tags:
              only: /.*/
      - test-backend:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
      - deploy-master:
          requires:
            - test-backend
            - test-frontend
            - build
          filters:
            branches:
              only: master
      - release:
          requires:
            - test-backend
            - test-frontend
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
